name: Run Azure Login with the Service Principal secret
on: [workflow_dispatch]

permissions:
      id-token: write
      contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login action
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
    
    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
          # You can write your Azure CLI inline scripts here.
    - name: Download flag
      run: |
          az storage blob download \
            --account-name <STORAGE_ACCOUNT_NAME> \
            --container-name flag \
            --name flag.txt \
            --file flag.txt \
            --auth-mode login
      
    - name: Read flag
      run: cat flag.txt
